SELECT AVG(SEATS) as AVG_SEATS
FROM BUSES

SELECT DATE, STATION_LOCATION
FROM SCHEDULE
GROUP BY DATE , STATION_LOCATION

SELECT BUS_NUMBER, AGENCY
FROM BUSES
WHERE DEPARTURE_LOCATION = 'Бургас'
GROUP BY AGENCY, BUS_NUMBER

SELECT COUNT(BUS_NUMBER) as BUS_NUM_COUNT
FROM BUSES
WHERE AGENCY = 'Юнион - Ивкони ООД'

SELECT TICKET_NUMBER, BUS_NUMBER, TYPE
FROM TICKETS 
WHERE CASHIER_NUMBER = '005'
GROUP BY TYPE, TICKET_NUMBER, BUS_NUMBER,

SELECT TICKET_NUMBER, SORT, ARRIVAL_LOCATION
FROM TICKETS
WHERE SORT = 'R'
GROUP BY ARRIVAL_LOCATION, TICKET_NUMBER, SORT

SELECT BUS_NUMBER, AGENCY
FROM BUSES 
WHERE ARRIVAL_LOCATION = 'София'
GROUP BY AGENCY, BUS_NUMBER

SELECT AVG(CURRENT_FREE_SEATS) as AVG_FREE SEATS
FROM BUSES
WHERE AGENCY = 'Експрес Снежанка ООД'

SELECT BUS_NUMBER, DEPARTURE_LOCATION, ARRIVAL_LOCATION
FROM BUSES
GROUP BY DEPARTURE_LOCATION, BUS_NUMBER, ARRIVAL_LOCATION

SELECT COUNT(BUS_NUMBER) as BUS_NUM_COUNT, AGENCY
FROM BUSES
GROUP BY AGENCY
