USE master
GO
if exists (select * from sysdatabases where name='bus_station')
	DROP DATABASE bus_station
GO

CREATE DATABASE bus_station
GO
USE bus_station
GO

CREATE TABLE BUS_STATION(
    LOCATION VARCHAR(100) NOT NULL PRIMARY KEY
);
CREATE TABLE CASHIERS(
    WORK_NUMBER INTEGER NOT NULL PRIMARY KEY ,
    PHONE CHAR(10), CHECK ( PHONE LIKE '[0][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' ),
    NAME VARCHAR(50)
);
CREATE TABLE PAY_DESKS(
    CASHIER_NUMBER INTEGER NOT NULL REFERENCES CASHIERS(WORK_NUMBER),
    STATION_LOCATION VARCHAR(100) NOT NULL REFERENCES BUS_STATION(LOCATION),
    PAY_DESK_NUMBER INTEGER NOT NULL,
	AGENCY VARCHAR(50) NOT NULL,
    PRIMARY KEY (CASHIER_NUMBER, STATION_LOCATION, PAY_DESK_NUMBER)
);

CREATE TABLE BUSES(
    BUS_NUMBER INTEGER UNIQUE NOT NULL ,
    DEPARTURE_LOCATION VARCHAR(100) NOT NULL REFERENCES BUS_STATION(LOCATION),
    ARRIVAL_LOCATION VARCHAR(100) NOT NULL REFERENCES BUS_STATION(LOCATION),
    SEATS INTEGER CHECK (SEATS < 60),
    DEPARTURE_DATE_AND_HOUR DATETIME DEFAULT GETDATE(),
    ARRIVAL_DATE__AND_HOUR DATETIME DEFAULT GETDATE(),
	AGENCY VARCHAR(50) NOT NULL,
    PRIMARY KEY(BUS_NUMBER, DEPARTURE_LOCATION, ARRIVAL_LOCATION)
);

CREATE TABLE DRIVERS(
    DRIVER_NUMBER INTEGER NOT NULL PRIMARY KEY ,
    PHONE CHAR(10) CHECK ( PHONE LIKE '0[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' ),
    NAME VARCHAR(50) NOT NULL
);
CREATE TABLE DRIVE(
    DRIVER_NUMBER INTEGER NOT NULL REFERENCES DRIVERS(DRIVER_NUMBER),
    BUS_NUMBER INTEGER NOT NULL REFERENCES BUSES(BUS_NUMBER),
    PRIMARY KEY(DRIVER_NUMBER,BUS_NUMBER)
);
CREATE TABLE PASSENGERS(
    PHONE CHAR(10) CHECK ( PHONE LIKE '0[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' ) PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL
);

CREATE TABLE TICKETS(
	TICKET_NUMBER CHAR(10) NOT NULL,
    BUS_NUMBER INTEGER NOT NULL REFERENCES BUSES(BUS_NUMBER),
    CASIER_NUMBER INTEGER NOT NULL REFERENCES CASHIERS(WORK_NUMBER),
    PASSENGER_PHONE CHAR(10) NOT NULL REFERENCES PASSENGERS(PHONE),
	DEPARTURE_LOCATION VARCHAR(100),
    SEAT INTEGER,
    DEPARTURE_DATE_AND_HOUR DATETIME DEFAULT GETDATE(),
    SORT CHAR(1) DEFAULT 'N' CHECK ( SORT in ('N', 'R')),
	TYPE CHAR(1) DEFAULT 'O' CHECK ( TYPE in ('O', 'T')),
	ÀÃÅÍÖÈß CHAR(10) NOT NULL,
    PRIMARY KEY(TICKET_NUMBER,BUS_NUMBER,CASIER_NUMBER,PASSENGER_PHONE)
);
CREATE TABLE SCHEDULE(
    DATE DATE PRIMARY KEY,
	STATION_LOCATION VARCHAR(100) NOT NULL REFERENCES BUS_STATION(LOCATION),
    DEPARTURE_LIST VARCHAR(3) CHECK ( DEPARTURE_LIST in ('yes', 'no')),
    ARRIVAL_LIST VARCHAR(3) CHECK ( ARRIVAL_LIST  in ('yes', 'no'))
);


